# Generated by Django 4.1.1 on 2022-09-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('item_rating', models.CharField(max_length=1000)),
                ('item_offers', models.EmailField(default='email', max_length=255)),
                ('item_price', models.IntegerField(default=0)),
                ('item_features', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Tamazon',
                'db_table': 'Tamazon',
            },
        ),
    ]
