# Generated by Django 4.1.1 on 2022-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamazon',
            name='item_offers',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
